[build]
  command = "npm run build && npm run serve:ssr:pokemon-ssr"
  publish = "dist/pokemon-ssr/browser"
  functions = "dist/pokemon-ssr/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200